behaviors:
  DroneAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16384
      buffer_size: 163840
      learning_rate: 3.0e-4
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: resnet
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.03
        gamma: 0.99
        learning_rate: 3.0e-4
    max_steps: 200000000
    time_horizon: 512
    summary_freq: 10000
    keep_checkpoints: 20
    checkpoint_interval: 250000
torch_settings:
  device: cuda
